entryPoints:
  web:
    address: ":8080"

api:
  dashboard: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: logic_net
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

log:
  level: INFO
